# Generated by Django 5.0.4 on 2024-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='orderline',
            name='vat_type',
            field=models.CharField(choices=[('standard', 'Standard (21%)'), ('reduced', 'Reducido (10,5%)'), ('zero', 'SIN IVA')], default='standard', max_length=100),
        ),
    ]
