# Generated by Django 5.0.4 on 2024-04-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.salesperson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
